In [ ]:
#Soft computing mini project - Classification use case

In [45]:
import pandas as pd
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report,precision_score, recall_score, f1_score

RANDOM_STATE = 42

In [28]:
path = "sms.txt"
df = pd.read_csv(path, sep="\t", header=None, names=["label", "message"])
df["label_num"] = df["label"].map({"ham": 0, "spam": 1})

print(f"Total messages: {len(df)}")
print(df["label"].value_counts())
df.head()

Total messages: 5572
label
ham     4825
spam     747
Name: count, dtype: int64

  label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

In [29]:
# Data cleansing

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[%s]" % re.escape(string.punctuation), " ", text)
    text = re.sub(r"\d+", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text
df["clean_message"] = df["message"].apply(clean_text)
df[["message", "clean_message"]].head()

,message,clean_message
0,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in a wkly comp to win fa cup final ...
3,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,"Nah I don't think he goes to usf, he lives aro...",nah i don t think he goes to usf he lives arou...

In [30]:
# Split the train and test datasets. Vectorize the train and test input features.

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df["clean_message"], df["label_num"],
    test_size=0.2, random_state=RANDOM_STATE, stratify=df["label_num"]
)
vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1, 2), min_df=2, max_df=0.95)

X_train = vectorizer.fit_transform(X_train_text)
X_test = vectorizer.transform(X_test_text)

print(f"Train shape: {X_train.shape}")
print(f"Test shape:  {X_test.shape}")

Train shape: (4457, 6766)
Test shape:  (1115, 6766)

In [47]:
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
print("🎉 Model training complete!")
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model accuracy score:\n",accuracy)

precision = precision_score(y_test, y_pred)
print("Model precision score:\n",precision)

recall = recall_score(y_test, y_pred)
print("Model recall score:\n",recall)

f1 = f1_score(y_test, y_pred)
print("Model f1 score:\n",recall)

#y_proba = model.predict_proba(X_test)

#print(classification_report(y_test, y_pred))

#print(y_pred)

🎉 Model training complete!
Model accuracy score:
 0.9704035874439462
Model precision score:
 1.0
Model recall score:
 0.7785234899328859
Model f1 score:
 0.7785234899328859